In [1]:
import pandas as pd
import numpy as np
from scipy.stats import mannwhitneyu, chi2_contingency
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

sns.set()
warnings.filterwarnings('ignore')

In [2]:
data = pd.read_csv('../data/gym_churn_us_clean.csv')
data.head()

,gender,near_location,partner,promo_friends,phone,contract_period,group_visits,age,avg_additional_charges_total,month_to_end_contract,lifetime,avg_class_frequency_total,avg_class_frequency_current_month,churn,frequency_drop,age_group
0,1,1,1,1,0,6,1,29,14.227470,5.0,3,0.020398,0.000000,0,0.020398,26-35
1,0,1,0,0,1,12,1,31,113.202938,12.0,7,1.922936,1.910244,0,0.012693,26-35
2,0,1,1,0,1,1,0,28,129.448479,1.0,2,1.859098,1.736502,0,0.122596,26-35
3,0,1,1,1,1,12,1,33,62.669863,12.0,2,3.205633,3.357215,0,-0.151582,26-35
4,1,1,1,1,1,1,0,26,198.362265,1.0,3,1.113884,1.120078,0,-0.006194,26-35

Testing if the frequency drop is higher on churn positive members  
&darr; &darr; &darr;

In [3]:
churn_positive = data.loc[data['churn'] == 1, 'frequency_drop']
churn_negative = data.loc[data['churn'] == 0, 'frequency_drop']

u, p_value = mannwhitneyu(churn_negative, churn_positive, alternative='less')

print(f"U = {u}")
print(f"p value = {p_value}")

U = 553037.0
p value = 4.903036186178531e-214

&uarr; &uarr; &uarr;  
We used the mann-whitney u test because frequency drops' values on both groups are not normal distributed

##### Categorical Tests

Gender

In [4]:
gender_table = pd.crosstab(data['gender'], data['churn'])

chi2, pvalue, df, expected = chi2_contingency(gender_table)

n = gender_table.to_numpy().sum()
r, c = gender_table.shape
gender_cramers_v = np.sqrt(chi2 / (n * min(r-1,c-1)))

print(f"Chi2: {chi2}")
print(f"P-value: {pvalue}")
print(f"Degrees of Freedom: {df}")
print(f"Gender Table:")
print(f"{gender_table}")
print(f"Expected:")
print(f"{expected}")
print(f"Cramer's V:")
print(f"{gender_cramers_v}")

Chi2: 7.988563135775134e-05
P-value: 0.9928687015043638
Degrees of Freedom: 1
Gender Table:
churn      0    1
gender
0       1440  519
1       1499  542
Expected:
[[1439.37525  519.62475]
 [1499.62475  541.37525]]
Cramer's V:
0.0001413202315290979

Joined by 'bring a friend' promo

In [5]:
friend_table = pd.crosstab(data['promo_friends'], data['churn'])

chi2, pvalue, df, expected = chi2_contingency(friend_table)

n = friend_table.to_numpy().sum()
r, c = friend_table.shape

friend_cramers_v = np.sqrt(chi2/(n*min(r-1,c-1)))

print(f"Chi2: {chi2}")
print(f"P-value: {pvalue}")
print(f"Degrees of Freedom: {df}")
print(f"Friend Table:")
print(f"{friend_table}")
print(f"Expected:")
print(f"{expected}")
print(f"Cramer's V:")
print(f"{friend_cramers_v}")

Chi2: 104.48414646175607
P-value: 1.584561975964236e-24
Degrees of Freedom: 1
Friend Table:
churn             0    1
promo_friends
0              1900  866
1              1039  195
Expected:
[[2032.3185  733.6815]
 [ 906.6815  327.3185]]
Cramer's V:
0.16162003779061251

Living or working near the gym

In [6]:
near_table = pd.crosstab(data['near_location'], data['churn'])

chi2, pvalue, df, expected = chi2_contingency(near_table)

n = near_table.to_numpy().sum()
r, c = near_table.shape

near_cramers_v = np.sqrt(chi2/(n*min(r-1,c-1)))

print(f"Chi2: {chi2}")
print(f"P-value: {pvalue}")
print(f"Degrees of Freedom: {df}")
print(f"Near Table:")
print(f"{near_table}")
print(f"Expected:")
print(f"{expected}")
print(f"Cramer's V:")
print(f"{near_cramers_v}")

Chi2: 64.83653197935402
P-value: 8.137638074792214e-16
Degrees of Freedom: 1
Near Table:
churn             0    1
near_location
0               373  246
1              2566  815
Expected:
[[ 454.81025  164.18975]
 [2484.18975  896.81025]]
Cramer's V:
0.12731509335046848

Attendance of group classes

In [7]:
group_table = pd.crosstab(data['group_visits'], data['churn'])

chi2, pvalue, df, expected = chi2_contingency(group_table)

n = group_table.to_numpy().sum()
r, c = group_table.shape

group_cramers_v = np.sqrt(chi2/(n*min(r-1,c-1)))

print(f"Chi2: {chi2}")
print(f"P-value: {pvalue}")
print(f"Degrees of Freedom: {df}")
print(f"Group Table:")
print(f"{group_table}")
print(f"Expected:")
print(f"{expected}")
print(f"Cramer's V:")
print(f"{group_cramers_v}")

Chi2: 122.14945732709342
P-value: 2.1408744660884118e-28
Degrees of Freedom: 1
Group Table:
churn            0    1
group_visits
0             1575  776
1             1364  285
Expected:
[[1727.39725  623.60275]
 [1211.60275  437.39725]]
Cramer's V:
0.17474943299413978

Joined by a partner companies membership discount

In [8]:
partner_table = pd.crosstab(data['partner'], data['churn'])

chi2, pvalue, df, expected = chi2_contingency(partner_table)

n = partner_table.to_numpy().sum()
r, c = partner_table.shape

partner_cramers_v = np.sqrt(chi2/(n*min(r-1,c-1)))

print(f"Chi2: {chi2}")
print(f"P-value: {pvalue}")
print(f"Degrees of Freedom: {df}")
print(f"Partner Table:")
print(f"{partner_table}")
print(f"Expected:")
print(f"{expected}")
print(f"Cramer's V:")
print(f"{partner_cramers_v}")

Chi2: 99.12327266554365
P-value: 2.372635812097966e-23
Degrees of Freedom: 1
Partner Table:
churn       0    1
partner
0        1369  684
1        1570  377
Expected:
[[1508.44175  544.55825]
 [1430.55825  516.44175]]
Cramer's V:
0.15741924331664764

Contract periods effect on churn

In [9]:
contract_table = pd.crosstab(data['contract_period'], data['churn'])

chi2, pvalue, df, expected = chi2_contingency(contract_table)

n = contract_table.to_numpy().sum()
r, c = contract_table.shape

contract_cramers_v = np.sqrt(chi2/(n*min(r-1,c-1)))

print(f"Chi2: {chi2}")
print(f"P-value: {pvalue}")
print(f"Degrees of Freedom: {df}")
print(f"Contract Table:")
print(f"{contract_table}")
print(f"Expected:")
print(f"{expected}")
print(f"Cramer's V:")
print(f"{contract_cramers_v}")

Chi2: 653.5552193849468
P-value: 1.208613110644596e-142
Degrees of Freedom: 2
Contract Table:
churn               0    1
contract_period
1                1273  934
6                 729  104
12                937   23
Expected:
[[1621.59325  585.40675]
 [ 612.04675  220.95325]
 [ 705.36     254.64   ]]
Cramer's V:
0.40421381080591084

&uarr; &uarr; &uarr;  
We can ses there contract period have an effect on churn  
We would like to see, if the contract period increases, churn rate decreases  
&darr; &darr; &darr;

In [10]:
contract_period_gb = data.groupby('contract_period')['churn'].agg(churn_rate='mean')
print(contract_period_gb)

                 churn_rate
contract_period
1                  0.423199
6                  0.124850
12                 0.023958

&uarr; &uarr; &uarr;  
This table shows that; longer the contract period is, churn rate declines

Age groups' effect on churn

In [11]:
age_group_table = pd.crosstab(data['age_group'], data['churn'])

chi2, pvalue, df, expected = chi2_contingency(age_group_table)

n = age_group_table.to_numpy().sum()
r, c = age_group_table.shape

age_group_cramers_v = np.sqrt(chi2/(n*min(r-1,c-1)))

print(f"Chi2: {chi2}")
print(f"P-value: {pvalue}")
print(f"Degrees of Freedom: {df}")
print(f"Age Group Table:")
print(f"{age_group_table}")
print(f"Expected:")
print(f"{expected}")
print(f"Cramer's V:")
print(f"{age_group_cramers_v}")

Chi2: 417.3991497476258
P-value: 2.3063555360422615e-91
Degrees of Freedom: 2
Age Group Table:
churn         0    1
age_group
18-25       204  332
26-35      2645  728
36+          90    1
Expected:
[[ 393.826    142.174  ]
 [2478.31175  894.68825]
 [  66.86225   24.13775]]
Cramer's V:
0.323032177092169

Checking for the same trend on age groups

In [12]:
age_group_gb = data.groupby('age_group')['churn'].agg(churn_rate='mean')
print(age_group_gb)

           churn_rate
age_group
18-25        0.619403
26-35        0.215832
36+          0.010989

In [20]:
cramers_v_data_frame = pd.DataFrame([
    "Gender", "Friend Discount", "Near Location", "Group Classes", "Partner Company", "Contract Period", "Age Group"], columns=['Variables'])
cramers_v_data_frame["Cramer's V"] = [
    gender_cramers_v, friend_cramers_v, near_cramers_v, group_cramers_v, partner_cramers_v, contract_cramers_v, age_group_cramers_v]
cramers_v_data_frame.sort_values(by=["Cramer's V"], ascending=False)

         Variables  Cramer's V
5  Contract Period    0.404214
6        Age Group    0.323032
3    Group Classes    0.174749
1  Friend Discount    0.161620
4  Partner Company    0.157419
2    Near Location    0.127315
0           Gender    0.000141

&uarr; &uarr; &uarr;  
This table shows how strong the veriables effect to churn by checking Cramer's V values.  
Around  
0.1 --> Not that strong  
0.3 --> Considerable  
0.5 --> Strong